services:
  forrest-gump-app:
    container_name: forrest-gump-app
    build:
      context: .
      dockerfile: Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
